server:
  port: 80

spring:
  application:
    name: cloud-openfeign-order-service

eureka:
  client:
    register-with-eureka: true #表示是否将自己注册进EurekaServer默认为true。
    fetch-registry: true #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      #defaultZone: http://localhost:7001/eureka #单机版
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/ #集群版
  instance:
    instance-id: openFeignOrder80
    #访问路径可以显示IP地址
    prefer-ip-address: true

#设置feign客户端超时时间(OpenFeign默认支持ribbon)单位：毫秒
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况-两端连接所用的时间
  ReadTimeout: 5000
  #指的是建立连接后服务端读取到可用资源所用的时间
  ConnectTimeout: 5000

#开启feign客户端日志记录
logging:
  level:
    #feign客户端日志以什么级别监控哪个接口
    com.hzg.cloud.feignservice.PaymentServiceClient: DEBUG
