spring:
  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3308/mybatis_plus?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: root
    dynamic:
      primary: master # 设置默认的数据源或者数据源组，默认值即为master
      strict: false # 严格匹配数据源，默认false，true未匹配到指定数据源时抛异常，false使用默认数据源
      datasource:
        # 会配置一个默认库master，一个组slave下有两个子库slave_1，slave_2
        master:
          url: jdbc:mysql://localhost:3308/mybatis_plus?useUnicode=true&characterEncoding=utf-8&useSSL=false
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver # 3.2.0开始支持SPI可省略此配置
        slave_1:
          url: jdbc:mysql://localhost:3308/mybatis_plus1?useUnicode=true&characterEncoding=utf-8&useSSL=false
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver

## mybatis-plus配置
mybatis-plus:
  type-handlers-package: com.hzg.mybatisplus.mapper
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.hzg.mybatisplus.pojo # 配置类型别名所对应的包：resultType可以直接使用类别名(默认就是类名)
  type-enums-package: com.hzg.mybatisplus.pojo.enums # 通用枚举的包
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印sql日志
  # mybatis-plus全局配置
  global-config:
    db-config:
#      table-prefix: "tb_" # 全局设置表名前缀
#      id-type: auto # 全局设置主键生成策略
      logic-delete-field: deleted # 全局设置逻辑删除字段名
      logic-delete-value: 1       # 全局设置逻辑已删除值
      logic-not-delete-value: 0   # 全局设置逻辑未删除值
