server:
  port: 9527

spring:
  application:
    name: cloud-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
      - id: payment_routh #payment_route     #路由的ID，没有固定规则但要求唯一，建议配合服务名
        #uri: http://localhost:8001          #匹配后提供服务的路由地址
        uri: lb://cloud-payment-service      #匹配后提供服务的路由地址
        predicates:
        - Path=/payment/getPaymentById/**    #断言，路径相匹配的进行路由

      - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
        #uri: http://localhost:8001          #匹配后提供服务的路由地址
        uri: lb://cloud-payment-service      #匹配后提供服务的路由地址
        predicates:
        - Path=/payment/getLoadBalancer/**   #断言，路径相匹配的进行路由
        #- After=2021-08-29T14:26:33.044+08:00[Asia/Shanghai]
        #- Before=2021-08-29T15:26:33.044+08:00[Asia/Shanghai]
        #- Between=2021-08-29T14:26:33.044+08:00[Asia/Shanghai],2021-08-29T15:26:33.044+08:00[Asia/Shanghai]
        #- Cookie=username,oasis
        #- Header=X-Request-Id, \d+  # 请求头要有X-Request-Id属性并且值为整数的正则表达式

eureka:
  client:
    register-with-eureka: true #表示是否将自己注册进EurekaServer默认为true。
    fetch-registry: true       #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: cloudGateway9527
