#8004表示注册到zookeeper服务器的支付服务提供者的端口号
server:
  port: 8004

spring:
  application:
    name: cloud-paymentzk-service #服务别名--注册到zookeeper注册中心的名称
  cloud:
    zookeeper:
      connect-string: 121.196.163.155:2181
